### ISSUE TITLE
Subscriptions Disappear on Page Refresh

### ISSUE THREAD

**Issue by jmhoskinson** [pozil/streaming-monitor#34]
I have change data capture turned on and configured for the objects I'm subscribing to (Account and Contact). When I successfully subscribe the to CDC events, I can see a toast message showing the record updates I make on another tab, but when I refresh the tab I subscribed to the events in, it shows no subscriptions and the streaming monitor shows no data.

**Comment by pozil** [comment]
Hi @jmhoskinson this is the standard behavior for the base [lightning/empApi](https://developer.salesforce.com/docs/component-library/bundle/lightning-emp-api/documentation) module that handles streaming API subscriptions. Because of the underlying technology, we cannot keep the connections open when a page is refreshed.

The only thing that I could do would be to save the subscribed channel names in a cookie and then re-open them programmatically when the page reloads. However, even I did this, you would miss the last CDC event that was triggered in the other tab so it's not really a viable solution. I recommend keeping the streaming monitor open in a separate browser tab and run you record changes in another browser tab.
